import { z } from "zod";

import { readPublicCatalog } from "@/features/organizations/public-catalog";
import { apiError, apiException, apiSuccess } from "@/lib/api/response";

// Needs Node (createSupabaseAdminClient), matching booking-intent/route.ts.
export const runtime = "nodejs";

type Context = { params: Promise<{ organizationId: string }> };

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
} as const;

// The repo has no CORS handling or middleware anywhere, so a cross-origin
// browser fetch() from an external booking website would otherwise be
// blocked silently. This data is public and carries no credentials.
const SUCCESS_HEADERS = {
  ...CORS_HEADERS,
  "Cache-Control": "public, s-maxage=60, stale-while-revalidate=300",
};
const NOT_AVAILABLE_HEADERS = {
  ...CORS_HEADERS,
  "Cache-Control": "no-store",
};

// Public, unauthenticated by design: an external booking website (outside
// this repo, possibly generated by an AI agent with no access to this
// codebase) fetches this to discover the organization's salon/service/
// technician UUIDs, timezone, and hours before building its own booking UI.
// See docs/architecture/authorization.md and docs/integrations/
// external-booking-website.md.
export async function GET(_request: Request, { params }: Context) {
  try {
    const { organizationId } = await params;
    // A malformed ID, an unknown ID, and an archived organization all return
    // the same 404 so the endpoint is not an enumeration oracle.
    const parsedId = z.uuid().safeParse(organizationId);
    const catalog = parsedId.success ? await readPublicCatalog(parsedId.data) : null;
    if (!catalog) {
      return withHeaders(
        apiError("organization_not_available", "This organization is not available", 404),
        NOT_AVAILABLE_HEADERS,
      );
    }

    return withHeaders(apiSuccess(catalog), SUCCESS_HEADERS);
  } catch (error) {
    return apiException(error);
  }
}

export function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      ...CORS_HEADERS,
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Max-Age": "86400",
    },
  });
}

function withHeaders(response: Response, headers: Record<string, string>) {
  for (const [key, value] of Object.entries(headers)) response.headers.set(key, value);
  return response;
}
